baseurl = "https://erdaniels.com"
languageCode = "en-us"
title = "Eric Daniels - Software Engineer"
theme = "erdanielsdotcom"
copyright = "Eric Daniels"
Paginate = 5

[Author]
	name = "Eric Daniels"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"

[params]
	description = "code; stuff;"

	# Comments
	disqus = "erdaniels"

	# Social media
	facebook = "https://www.facebook.com/EricDaniels"
	github = "https://github.com/edaniels"
	linkedin = "https://www.linkedin.com/in/erdaniels"
	twitter = "https://twitter.com/ericrdaniels"


